# Generated by Django 6.0.4 on 2026-04-16 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_kr', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('target_type', models.CharField(choices=[('HODIM', 'Hodim'), ('TASHKILOT', 'Tashkilot')], max_length=15)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('position_uz', models.CharField(max_length=255)),
                ('position_kr', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255)),
                ('agency_uz', models.CharField(max_length=255)),
                ('agency_kr', models.CharField(max_length=255)),
                ('agency_ru', models.CharField(max_length=255)),
                ('agency_en', models.CharField(max_length=255)),
                ('desc_uz', models.TextField()),
                ('desc_kr', models.TextField()),
                ('desc_ru', models.TextField()),
                ('desc_en', models.TextField()),
                ('working_hours', models.CharField(max_length=100)),
                ('tags_uz', models.TextField(blank=True)),
                ('tags_kr', models.TextField(blank=True)),
                ('tags_ru', models.TextField(blank=True)),
                ('tags_en', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_uz', models.TextField()),
                ('question_kr', models.TextField()),
                ('question_ru', models.TextField()),
                ('question_en', models.TextField()),
                ('answer_uz', models.TextField()),
                ('answer_kr', models.TextField()),
                ('answer_ru', models.TextField()),
                ('answer_en', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='api_v1.faqcategory')),
            ],
        ),
    ]
