# Generated by Django 6.0.4 on 2026-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_rename_phone_number_applicationtarget_phone_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtarget',
            name='temp_password',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
