# Generated by Django 6.0.4 on 2026-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_applicationtarget_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtarget',
            name='work_days',
            field=models.CharField(choices=[('Monday-Friday', 'Monday - Friday'), ('Monday-Saturday', 'Monday - Saturday'), ('Monday-Sunday', 'Monday - Sunday'), ('Shift 1', 'Shift 1 (Morning)'), ('Shift 2', 'Shift 2 (Evening)'), ('Custom', 'Custom Schedule')], default='Monday-Friday', help_text='Select working days', max_length=50),
        ),
        migrations.AddField(
            model_name='applicationtarget',
            name='work_end',
            field=models.TimeField(blank=True, help_text='End time (e.g., 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='applicationtarget',
            name='work_start',
            field=models.TimeField(blank=True, help_text='Start time (e.g., 08:00)', null=True),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
