# Generated by Django 6.0.4 on 2026-04-16 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_applicationtarget_work_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtarget',
            name='agency_en',
            field=models.CharField(max_length=255, verbose_name='Tashkilot (Inglizcha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='agency_kr',
            field=models.CharField(max_length=255, verbose_name='Tashkilot (Qoraqalpoq)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='agency_ru',
            field=models.CharField(max_length=255, verbose_name='Tashkilot (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='agency_uz',
            field=models.CharField(max_length=255, verbose_name="Tashkilot (O'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='desc_en',
            field=models.TextField(verbose_name='Tavsif (Inglizcha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='desc_kr',
            field=models.TextField(verbose_name='Tavsif (Qoraqalpoq)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='desc_ru',
            field=models.TextField(verbose_name='Tavsif (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='desc_uz',
            field=models.TextField(verbose_name="Tavsif (O'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='image',
            field=models.ImageField(upload_to='profiles/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='position_en',
            field=models.CharField(max_length=255, verbose_name='Lavozim (Inglizcha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='position_kr',
            field=models.CharField(max_length=255, verbose_name='Lavozim (Qoraqalpoq)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='position_ru',
            field=models.CharField(max_length=255, verbose_name='Lavozim (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='position_uz',
            field=models.CharField(max_length=255, verbose_name="Lavozim (O'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='tags_en',
            field=models.TextField(blank=True, verbose_name='Qidiruv teglari (Inglizcha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='tags_kr',
            field=models.TextField(blank=True, verbose_name='Qidiruv teglari (Qoraqalpoq)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='tags_ru',
            field=models.TextField(blank=True, verbose_name='Qidiruv teglari (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='tags_uz',
            field=models.TextField(blank=True, verbose_name="Qidiruv teglari (O'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='target_type',
            field=models.CharField(choices=[('HODIM', 'Hodim'), ('TASHKILOT', 'Tashkilot')], max_length=15, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='work_days',
            field=models.CharField(choices=[('Dushanba-Juma', 'Dushanba - Juma'), ('Dushanba-Shanba', 'Dushanba - Shanba'), ('Dushanba-Yakshanba', 'Dushanba - Yakshanba'), ('1-smena', '1-smena (Tonggi)'), ('2-smena', '2-smena (Kechki)'), ('Maxsus', 'Maxsus jadval')], default='Dushanba-Juma', help_text='Ish kunlarini tanlang', max_length=50, verbose_name='Ish kunlari'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='work_end',
            field=models.TimeField(blank=True, help_text='Tugash vaqti (masalan, 17:00)', null=True, verbose_name='Ish tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='work_start',
            field=models.TimeField(blank=True, help_text='Boshlanish vaqti (masalan, 08:00)', null=True, verbose_name='Ish boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(verbose_name='Javob (Inglizcha)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_kr',
            field=models.TextField(verbose_name='Javob (Qoraqalpoq)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(verbose_name='Javob (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(verbose_name="Javob (O'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='api_v1.faqcategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(verbose_name='Savol (Inglizcha)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_kr',
            field=models.TextField(verbose_name='Savol (Qoraqalpoq)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(verbose_name='Savol (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.TextField(verbose_name="Savol (O'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Ikona'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Nomi (Inglizcha)'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_kr',
            field=models.CharField(max_length=255, verbose_name='Nomi (Qoraqalpoq)'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Nomi (Ruscha)'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_uz',
            field=models.CharField(max_length=255, verbose_name="Nomi (O'zbekcha)"),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='messages/', verbose_name='Media fayl'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=255, verbose_name='Yuboruvchi ismi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Matn'), ('audio', 'Audio'), ('video', 'Video')], default='text', max_length=10, verbose_name='Turi'),
        ),
    ]
