# Generated by Django 6.0.4 on 2026-04-16 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0006_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True, verbose_name='Session ID')),
                ('language', models.CharField(default='uz', max_length=5, verbose_name='Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Visit time')),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring_id', models.CharField(max_length=64, unique=True, verbose_name='Ring ID')),
                ('caller_name', models.CharField(default='Visitor', max_length=255, verbose_name='Caller name')),
                ('response', models.CharField(blank=True, choices=[('coming', 'Coming'), ('busy', 'Busy'), ('day_off', 'Day off')], max_length=10, verbose_name='Response')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rings', to='api_v1.applicationtarget', verbose_name='Target')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='view', max_length=20, verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='api_v1.applicationtarget', verbose_name='Target')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='api_v1.kioskvisit')),
            ],
        ),
    ]
