# Generated by Django 6.0.4 on 2026-04-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_kioskvisit_ring_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtarget',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="To'liq ism"),
        ),
    ]
