# Generated by Django 6.0.4 on 2026-04-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_add_kir_and_rename_kr_to_kk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtarget',
            name='agency_kir',
            field=models.CharField(max_length=255, verbose_name='Tashkilot (Kirilcha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='desc_kir',
            field=models.TextField(verbose_name='Tavsif (Kirilcha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='position_kir',
            field=models.CharField(max_length=255, verbose_name='Lavozim (Kirilcha)'),
        ),
        migrations.AlterField(
            model_name='applicationtarget',
            name='tags_kir',
            field=models.TextField(blank=True, verbose_name='Qidiruv teglari (Kirilcha)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_kir',
            field=models.TextField(verbose_name='Javob (Kirilcha)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_kir',
            field=models.TextField(verbose_name='Savol (Kirilcha)'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name_kir',
            field=models.CharField(max_length=255, verbose_name='Nomi (Kirilcha)'),
        ),
    ]
