# Generated by Django 6.0.4 on 2026-04-30 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_alter_applicationtarget_agency_kir_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tuman nomi')),
                ('slug', models.SlugField(help_text="URL identifier, e.g. 'oltiariq', 'boz'", max_length=60, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applicationtarget',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='kioskvisit',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='message',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='ring',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rings', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.CreateModel(
            name='DistrictAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='api_v1.district', verbose_name='Tuman')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='district_admin', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tuman admini',
                'verbose_name_plural': 'Tuman adminlari',
            },
        ),
    ]
