# Generated by Django 6.0.4 on 2026-04-30 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0012_backfill_default_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtarget',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='kioskvisit',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='message',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rings', to='api_v1.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='api_v1.district', verbose_name='Tuman'),
        ),
    ]
